---
Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
     #Bucket name has to be unique in S3
     BucketName: privates3bucketvs2020
     AccessControl: Private
